title : Software Testing
tagline: Testing Software
author : 
  name : Bored Really
  email : Supermcooldaddy@gmail.com	
  github : BoredReally
  twitter : BoredReally

navigation :
  - archive.html
  - categories.html
  - pages.html
  - about.md
  
